

#Buffer_Test: Buffer_Test.cpp
#	gcc -Wall -o Buffer_Test Buffer_Test.cpp -I../include/ -lcollider++ -lstdc++

#Node_Test: Node_Test.cpp 
#	gcc -Wall -o Node_Test Node_Test.cpp -I../include/ -lcollider++ -lstdc++

#Bus_Test: Bus_Test.cpp 
#	gcc -Wall -o Bus_Test Bus_Test.cpp -I../include/ -lcollider++ -lstdc++

#Grain_Test: Grain_Test.cpp
#	gcc -Wall -o Grain_Test Grain_Test.cpp -I../include/ -lcollider++ -lstdc++

#all: Sound_Test Client_Server_Test

#Sound_Test: Sound_Test.cpp 
#	gcc -Wall -o Sound_Test Sound_Test.cpp -I../include/ -lcollider++ -lstdc++

Client_Server_Test: Client_Server_Test.cpp
	gcc -Wall -o Client_Server_Test Client_Server_Test.cpp -I../include/ -I../include/tny_osc -lcollider++ -lstdc++


clean:
	rm Client_Server_Test #Sound_Test
